export const ModalSettingsInitialState = {
  title: 'New Chart',
  titleColor: '',
//   titleStyle: '',
//   titleSize: '',
  subtitle: '',
  subtitleColor: '',
//   subtitleStyle: '',
//   subtitleSize: '',
  xAxis: 'X-Axis',
  yAxis: 'Y-Axis',
  chartColor: '',
  backgroundColor: '',
  displayColorPicker: false,
  displayColorPickerSubtitle: false,
  displayColorPickerChart: false,
  displayColorPickerBackground: false,
//   chartType: '',
  titleStyle: [
    { value: null, label: 'Default' },
    { value: 'bold', label: 'Bold' },
    { value: 'italic', label: 'Italic' },
  ],
  selectedTitleStyle: 'Default',
  subtitleStyle: [
    { value: null, label: 'Default' },
    { value: 'bold', label: 'Bold' },
    { value: 'italic', label: 'Italic' },
  ],
  selectedSubtitleStyle: 'Default',
  titleSize: [
    { value: '14', label: '14' },
    { value: '16', label: '16' },
    { value: '18', label: '18' },
    { value: '20', label: '20' },
    { value: '22', label: '22' },
    { value: '24', label: '24' },
  ],
  selectedTitleSize: '14',
  subtitleSize: [
    { value: '14', label: '14' },
    { value: '16', label: '16' },
    { value: '18', label: '18' },
    { value: '20', label: '20' },
    { value: '22', label: '22' },
    { value: '24', label: '24' },
  ],
  selectedsubTitleSize: '14',
  chartType: [
    { value: 'line', label: 'Default' },
    { value: 'column', label: 'Column' },
    { value: 'spline', label: 'Spline' },
    { value: 'areaspline', label: 'AreaSpline' },
    { value: 'scatter', label: 'Scatter' },
    { value: 'bar', label: 'Bar' },
  ],
  selectedChartType: 'Default',
};
